export * from './About';
export * from './Contact';
export * from './Experience';
export * from './FeedBack';
export * from './Hero';
export * from './Navbar';
export * from './StarsCanvas';
export * from './TechStack';
export * from './Works';
